#name: empty_testing_app
name: ej2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: GreatVibe
      fonts:
        - asset: assets/fonts/Great_Vibes/GreatVibes-Regular.ttf
    - family: Salium
      fonts:
        - asset: assets/fonts/Salium/Salium.ttf
    - family: fotoCielo1
      fonts:
        - asset: /Users/Tardes/Desktop/FlutterDef/Flutter3k/empty_testing_app/assets/images/imagen1.jpg
    - family: fotoCielo2
      fonts:
        - asset: /Users/Tardes/Desktop/FlutterDef/Flutter3k/empty_testing_app/assets/images/imagen2.jpg

        #puedes poner fonts: assets: assets/image directamente para que coja todas las imagenes

  uses-material-design: true
